name = "settings"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "eac36d05dde74b7aaa73661fdabe1b48" }
]
